/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkir;
import java.lang.Math;
import java.time.Clock;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Calvin C M
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        formBox = new javax.swing.JPanel();
        labelInputNoKendaraan = new javax.swing.JLabel();
        labelInputJenisKendaraan = new javax.swing.JLabel();
        labelInputJamMasuk = new javax.swing.JLabel();
        labelInputJamKeluar = new javax.swing.JLabel();
        inputNoKendaraan = new javax.swing.JTextField();
        inputJenisKendaraan = new javax.swing.JComboBox<>();
        inputJamMasuk = new javax.swing.JTextField();
        inputJamKeluar = new javax.swing.JTextField();
        cekBiayaButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        waktuSekarangMasuk = new javax.swing.JButton();
        waktuSekarangKeluar = new javax.swing.JButton();
        hasilBox = new javax.swing.JPanel();
        labelHasilNoKendaraan = new javax.swing.JLabel();
        labelHasilJenisKendaraan = new javax.swing.JLabel();
        labelHasilJamMasuk = new javax.swing.JLabel();
        labelHasilJamKeluar = new javax.swing.JLabel();
        labelHasilLamaParkir = new javax.swing.JLabel();
        labelHasilBiayaParkir = new javax.swing.JLabel();
        hasilNoKendaraan = new javax.swing.JLabel();
        hasilJenisKendaraan = new javax.swing.JLabel();
        hasilJamMasuk = new javax.swing.JLabel();
        hasilJamKeluar = new javax.swing.JLabel();
        hasilLamaParkir = new javax.swing.JLabel();
        hasilBiayaParkir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        judul.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        judul.setText("Biaya Parkir");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        formBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));

        labelInputNoKendaraan.setText("No. Kendaraan");

        labelInputJenisKendaraan.setText("Jenis Kendaraan");

        labelInputJamMasuk.setText("Jam Masuk");

        labelInputJamKeluar.setText("Jam Keluar");

        inputJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));

        cekBiayaButton.setText("Cek Biaya");
        cekBiayaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBiayaButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        waktuSekarangMasuk.setText("Waktu Sekarang");
        waktuSekarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuSekarangMasukActionPerformed(evt);
            }
        });

        waktuSekarangKeluar.setText("Waktu Sekarang");
        waktuSekarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuSekarangKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBoxLayout = new javax.swing.GroupLayout(formBox);
        formBox.setLayout(formBoxLayout);
        formBoxLayout.setHorizontalGroup(
            formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelInputNoKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelInputJenisKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(labelInputJamMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelInputJamKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNoKendaraan)
                    .addComponent(inputJenisKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formBoxLayout.createSequentialGroup()
                        .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputJamMasuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formBoxLayout.createSequentialGroup()
                                .addComponent(cekBiayaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton))
                            .addComponent(inputJamKeluar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waktuSekarangMasuk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(waktuSekarangKeluar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        formBoxLayout.setVerticalGroup(
            formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInputNoKendaraan)
                    .addComponent(inputNoKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInputJenisKendaraan)
                    .addComponent(inputJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInputJamMasuk)
                    .addComponent(inputJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waktuSekarangMasuk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInputJamKeluar)
                    .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(waktuSekarangKeluar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekBiayaButton)
                    .addComponent(resetButton))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        hasilBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        labelHasilNoKendaraan.setText("No. Kendaraan");

        labelHasilJenisKendaraan.setText("Jenis Kendaraan");

        labelHasilJamMasuk.setText("Jam Masuk");

        labelHasilJamKeluar.setText("Jam Keluar");

        labelHasilLamaParkir.setText("Lama Parkir");

        labelHasilBiayaParkir.setText("Biaya Parkir");

        hasilNoKendaraan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hasilNoKendaraan.setPreferredSize(new java.awt.Dimension(40, 18));

        hasilJenisKendaraan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hasilJenisKendaraan.setPreferredSize(new java.awt.Dimension(40, 18));

        hasilJamMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hasilJamMasuk.setPreferredSize(new java.awt.Dimension(40, 18));

        hasilJamKeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hasilJamKeluar.setPreferredSize(new java.awt.Dimension(40, 18));

        hasilLamaParkir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hasilLamaParkir.setPreferredSize(new java.awt.Dimension(40, 18));

        hasilBiayaParkir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hasilBiayaParkir.setPreferredSize(new java.awt.Dimension(40, 18));

        javax.swing.GroupLayout hasilBoxLayout = new javax.swing.GroupLayout(hasilBox);
        hasilBox.setLayout(hasilBoxLayout);
        hasilBoxLayout.setHorizontalGroup(
            hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelHasilNoKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelHasilJenisKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(labelHasilJamMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelHasilJamKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelHasilLamaParkir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelHasilBiayaParkir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasilNoKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasilJenisKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasilJamMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasilJamKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasilLamaParkir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasilBiayaParkir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        hasilBoxLayout.setVerticalGroup(
            hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHasilNoKendaraan)
                    .addComponent(hasilNoKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHasilJenisKendaraan)
                    .addComponent(hasilJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHasilJamMasuk)
                    .addComponent(hasilJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHasilJamKeluar)
                    .addComponent(hasilJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHasilLamaParkir)
                    .addComponent(hasilLamaParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hasilBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHasilBiayaParkir)
                    .addComponent(hasilBiayaParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasilBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasilBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekBiayaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBiayaButtonActionPerformed
        Parkir parkir=new Parkir();
        parkir.setNoKendaraan(inputNoKendaraan.getText());
        parkir.setJenisKendaraan((String)inputJenisKendaraan.getSelectedItem());
        try {
            String[] masuk=inputJamMasuk.getText().split(":");
            String[] keluar=inputJamKeluar.getText().split(":");
            
            parkir.getDatang().setJam(Integer.parseInt(masuk[0]));
            parkir.getDatang().setMenit(Integer.parseInt(masuk[1]));
            parkir.getDatang().setDetik(Integer.parseInt(masuk[2]));
            parkir.getPulang().setJam(Integer.parseInt(keluar[0]));
            parkir.getPulang().setMenit(Integer.parseInt(keluar[1]));
            parkir.getPulang().setDetik(Integer.parseInt(keluar[2]));
            if(formatWaktuIsInvalid(parkir.getDatang()) || formatWaktuIsInvalid(parkir.getPulang())) {
                throw new InvalidTimeFormatException();
            }
            
            if(inputWaktuIsInvalid(parkir.getDatang(), parkir.getPulang())) {
                throw new InvalidTimeInputException();
            }
            
            hasilJamMasuk.setText(parkir.getDatang().toString());
            hasilJamKeluar.setText(parkir.getPulang().toString());
            hasilLamaParkir.setText(parkir.getLamaParkir().toString());
            hasilBiayaParkir.setText(String.valueOf(parkir.getBiayaParkir()));
            
        } catch(InvalidTimeFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Ada kesalahan!", 1);
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Yang anda masukkan bukan angka, silahkan coba lagi", "Ada kesalahan!", 1);
        } catch(InvalidTimeInputException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Ada kesalahan!", 1);
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Ada kesalahan!", 1);
        }
        
        hasilNoKendaraan.setText(parkir.getNoKendaraan());
        hasilJenisKendaraan.setText(parkir.getJenisKendaraan());
    }//GEN-LAST:event_cekBiayaButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // Reset input
        inputNoKendaraan.setText("");
        inputJamMasuk.setText("");
        inputJamKeluar.setText("");
        
        // Reset hasil
        hasilNoKendaraan.setText("");
        hasilJenisKendaraan.setText("");
        hasilJamMasuk.setText("");
        hasilJamKeluar.setText("");
        hasilBiayaParkir.setText("");
        
        inputNoKendaraan.requestFocus();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void waktuSekarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuSekarangMasukActionPerformed
        String[] jamMasuk=String.valueOf(LocalTime.now()).split(":");
        
        double detik=Double.parseDouble(jamMasuk[2]);
        int temp=(int)Math.ceil(detik);
        inputJamMasuk.setText(jamMasuk[0]+":"+jamMasuk[1]+":"+temp);
    }//GEN-LAST:event_waktuSekarangMasukActionPerformed

    private void waktuSekarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuSekarangKeluarActionPerformed
        String[] jamKeluar=String.valueOf(LocalTime.now()).split(":");
        
        double detik=Double.parseDouble(jamKeluar[2]);
        int temp=(int)Math.ceil(detik);
        inputJamKeluar.setText(jamKeluar[0]+":"+jamKeluar[1]+":"+temp);
    }//GEN-LAST:event_waktuSekarangKeluarActionPerformed

    public boolean formatWaktuIsInvalid(Waktu waktu) {
        return (
            (waktu.getJam() < 0 || waktu.getJam() > 24)
            &&
            (waktu.getMenit() < 0 || waktu.getMenit() > 59)
            &&
            (waktu.getDetik() < 0 || waktu.getDetik() > 59)
        );
    }
    
    public boolean inputWaktuIsInvalid(Waktu datang, Waktu pulang) {
        return (
            (datang.getJam() > pulang.getJam())
            &&
            (
                datang.getJam() < pulang.getJam()
                &&
                datang.getMenit() > pulang.getMenit()
            )
            &&
            (
                datang.getJam() < pulang.getJam()
                &&
                datang.getMenit() < pulang.getMenit()
                &&
                datang.getDetik() > pulang.getDetik()
            )
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekBiayaButton;
    private javax.swing.JPanel formBox;
    private javax.swing.JLabel hasilBiayaParkir;
    private javax.swing.JPanel hasilBox;
    private javax.swing.JLabel hasilJamKeluar;
    private javax.swing.JLabel hasilJamMasuk;
    private javax.swing.JLabel hasilJenisKendaraan;
    private javax.swing.JLabel hasilLamaParkir;
    private javax.swing.JLabel hasilNoKendaraan;
    private javax.swing.JPanel header;
    private javax.swing.JTextField inputJamKeluar;
    private javax.swing.JTextField inputJamMasuk;
    private javax.swing.JComboBox<String> inputJenisKendaraan;
    private javax.swing.JTextField inputNoKendaraan;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel labelHasilBiayaParkir;
    private javax.swing.JLabel labelHasilJamKeluar;
    private javax.swing.JLabel labelHasilJamMasuk;
    private javax.swing.JLabel labelHasilJenisKendaraan;
    private javax.swing.JLabel labelHasilLamaParkir;
    private javax.swing.JLabel labelHasilNoKendaraan;
    private javax.swing.JLabel labelInputJamKeluar;
    private javax.swing.JLabel labelInputJamMasuk;
    private javax.swing.JLabel labelInputJenisKendaraan;
    private javax.swing.JLabel labelInputNoKendaraan;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton waktuSekarangKeluar;
    private javax.swing.JButton waktuSekarangMasuk;
    // End of variables declaration//GEN-END:variables
}
